// RExtract - Flashback data extractor for the Atari ST
// Copyright (c) 2026 Neil Rackett
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Regenerate src/core/manifest.ts from a set of original disk images.
//
//   pnpm run manifest /path/to/disks
//
// The directory holds the four disks in any format the tool reads,
// named so they sort into disk order. Nothing from the disks themselves
// is written out: the manifest carries names, sizes and checksums only,
// which is what lets the tool tell a good dump from a bad one without
// this repository ever holding a byte of somebody's game.
//
// This is a developer tool. It is not part of the build, and it is
// never run in CI - there are no disks there to run it on.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { crc32 } from '../src/core/crc32';
import { readVolume } from '../src/core/amigados';
import { readImage } from '../src/core/read';
import { dataFileName, isWanted } from '../src/core/dataset';

const dir = process.argv[2];
if (!dir) {
	console.error('usage: pnpm run manifest <directory of disk images>');
	process.exit(2);
}

const names = readdirSync(dir)
	.filter((n) => /\.(adf|adz|ipf)$/i.test(n))
	.sort();
if (names.length !== 4) {
	console.error(`expected four disk images in ${dir}, found ${names.length}`);
	process.exit(1);
}

const disks = await Promise.all(names.map(async (name, i) => {
	const image = await readImage(name, new Uint8Array(readFileSync(join(dir, name))));
	const volume = readVolume(image);
	const files = volume.files
		.filter((f) => isWanted(f.path))
		.map((f) => ({
			src: f.path,
			out: dataFileName(f.path),
			size: f.size,
			crc32: crc32(f.bytes),
		}))
		.sort((a, b) => (a.out < b.out ? -1 : 1));
	console.error(`${name}: ${volume.name}, ${volume.filesystem}, ${files.length} wanted files`);
	return { disk: i + 1, volume: volume.name.toLowerCase(), files };
}));

const out = `// RExtract - Flashback data extractor for the Atari ST
// Copyright (c) 2026 Neil Rackett
// SPDX-License-Identifier: GPL-3.0-or-later
//
// The four Flashback Amiga disks, by name, size and checksum.
//
// GENERATED by tools/make-manifest.ts - do not edit by hand.
//
// This is how the tool tells the right disk from the wrong one, a good
// dump from a damaged one, and which of the four it is holding. There
// is no game data here and there never will be: names, byte counts and
// CRC32s only.

export interface KnownFile {
	/** Lower-cased path on the Amiga disk. */
	src: string;
	/** The name it takes in DATA/, uppercase and GEMDOS 8.3. */
	out: string;
	size: number;
	crc32: number;
}

export interface KnownDisk {
	disk: number;
	volume: string;
	files: KnownFile[];
}

export const KNOWN_DISKS: KnownDisk[] = [
${disks
		.map(
			(d) =>
				`	{
		disk: ${d.disk},
		volume: '${d.volume}',
		files: [
` +
				d.files
					.map(
						(f) =>
							`			{ src: '${f.src}', out: '${f.out}', size: ${f.size}, ` +
							`crc32: 0x${f.crc32.toString(16).padStart(8, '0')} },`,
					)
					.join('\n') +
				'\n\t\t],\n\t},',
		)
		.join('\n')}
];

/** Every name the finished DATA folder should hold. */
export const REQUIRED_FILES: string[] = [
${[...new Set(disks.flatMap((d) => d.files.map((f) => f.out)))]
		.sort()
		.map((n) => `	'${n}',`)
		.join('\n')}
];
`;

writeFileSync(new URL('../src/core/manifest.ts', import.meta.url), out);
console.error(`wrote src/core/manifest.ts: ${new Set(disks.flatMap((d) => d.files.map((f) => f.out))).size} unique files`);
